# Generated by Django 5.2.6 on 2025-12-09 02:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="listing",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="listingimage",
            options={"ordering": ["uploaded_at"]},
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.CharField(
                choices=[
                    ("furniture", "Furniture"),
                    ("electronics", "Electronics"),
                    ("textbooks", "Textbooks"),
                    ("clothing", "Clothing"),
                    ("donation", "Donation/Free"),
                    ("other", "Other"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("sold", "Sold"),
                    ("pending", "Pending"),
                ],
                db_index=True,
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="listingimage",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["is_active", "status", "-created_at"],
                name="marketplace_is_acti_593f53_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["seller", "-created_at"], name="marketplace_seller__290e30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["category", "is_active"], name="marketplace_categor_21a71c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingimage",
            index=models.Index(
                fields=["listing", "-uploaded_at"],
                name="marketplace_listing_538e79_idx",
            ),
        ),
    ]
