# Generated by Django 5.2.6 on 2025-11-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("sold", "Sold"),
                    ("pending", "Pending"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
