# Generated by Django 5.2.6 on 2025-11-15 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace', '0002_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='pickup_location',
            field=models.CharField(blank=True, help_text="Specify a safe pickup location for exchanges (e.g., 'UVA Library', 'Student Union')", max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('electronics', 'Electronics'), ('textbooks', 'Textbooks'), ('clothing', 'Clothing'), ('donation', 'Donation/Free'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Marketplace.listing'),
        ),
    ]
