# Generated by Django 5.2.6 on 2025-11-12 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Marketplace", "0002_listing_status"),
        ("messaging", "0002_remove_message_conteent_message_content_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="message", old_name="timestamp", new_name="created_at",
        ),
        migrations.RemoveField(model_name="message", name="content",),
        migrations.RemoveField(model_name="message", name="receiver",),
        migrations.AddField(
            model_name="message",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Marketplace.listing",
            ),
        ),
        migrations.AddField(
            model_name="message", name="text", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "context_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="message_threads",
                        to="Marketplace.listing",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="threads", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="messaging.thread",
            ),
        ),
    ]
