# Generated by Django 5.2.6 on 2025-11-12 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0004_notification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="threads", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ThreadParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unread_count", models.PositiveIntegerField(default=0)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_participants",
                        to="messaging.thread",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_participants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="thread",
            name="participants_new",
            field=models.ManyToManyField(
                blank=True,
                related_name="threads_new",
                through="messaging.ThreadParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="threadparticipant",
            index=models.Index(fields=["user"], name="messaging_t_user_id_b8997a_idx"),
        ),
        migrations.AddIndex(
            model_name="threadparticipant",
            index=models.Index(
                fields=["thread"], name="messaging_t_thread__3803b7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="threadparticipant", unique_together={("thread", "user")},
        ),
    ]
