# Generated by Django 5.2.6 on 2025-11-12 17:01

from django.db import migrations

def forwards(apps, schema_editor):
    Thread = apps.get_model("messaging", "Thread")
    ThreadParticipant = apps.get_model("messaging", "ThreadParticipant")
    for thread in Thread.objects.all():
        for user in thread.participants.all():
            ThreadParticipant.objects.get_or_create(thread=thread, user=user)
            thread.participants_new.add(user)

def backwards(apps, schema_editor):
    Thread = apps.get_model("messaging", "Thread")
    for thread in Thread.objects.all():
        thread.participants.clear()
        for tp in thread.thread_participants.all():
            thread.participants.add(tp.user)

class Migration(migrations.Migration):
    dependencies = [("messaging", "0005_add_threadparticipant_and_participants_new")]
    operations = [migrations.RunPython(forwards, backwards)]
