# Generated by Django 5.2.6 on 2025-11-12 17:02

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [("messaging", "0006_copy_participants_to_through")]
    operations = [migrations.RemoveField(model_name="thread", name="participants")]
