# Generated by Django 5.2.6 on 2025-11-12 17:02

from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [("messaging", "0007_drop_old_participants")]
    operations = [migrations.RenameField(model_name="thread", old_name="participants_new", new_name="participants")]

