# Generated by Django 5.2.6 on 2025-11-12 22:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0008_rename_participants_new_to_participants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="threads",
                through="messaging.ThreadParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
