# Generated by Django 5.2.6 on 2025-11-12 22:11

from django.db import migrations

def forwards(apps, schema_editor):
    Message = apps.get_model('messaging', 'Message')
    Thread = apps.get_model('messaging', 'Thread')
    ThreadParticipant = apps.get_model('messaging', 'ThreadParticipant')
    db = schema_editor.connection.alias

    # Backfill: for each orphaned message, create a minimal thread and attach sender.
    qs = Message.objects.using(db).filter(thread__isnull=True).only('id', 'sender_id', 'listing_id')
    for m in qs.iterator():
        t = Thread.objects.using(db).create(context_listing_id=m.listing_id)
        # ensure at least the sender is a participant
        ThreadParticipant.objects.using(db).get_or_create(thread=t, user_id=m.sender_id)
        Message.objects.using(db).filter(pk=m.pk).update(thread_id=t.id)

def reverse(apps, schema_editor):
    # No destructive reverse; leave threads/messages as-is.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_rename_participants_new_to_participants'),  # <-- update to your latest
    ]

    operations = [
        migrations.RunPython(forwards, reverse),
    ]
