# Generated by Django 5.2.6 on 2025-11-12 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0009_alter_thread_participants"),
        ("messaging", "0010_backfill_message_threads"),
    ]

    operations = []
