# Generated by Django 5.2.6 on 2025-11-12 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0011_merge_20251112_2216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="messaging.thread",
            ),
        ),
    ]
