# Generated by Django 5.2.6 on 2025-11-15 00:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0012_alter_message_thread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='group_name',
            field=models.CharField(blank=True, help_text='Name for group conversations', max_length=100),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Whether this is a group conversation'),
        ),
        migrations.AddField(
            model_name='threadparticipant',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archive this conversation'),
        ),
        migrations.AddField(
            model_name='threadparticipant',
            name='is_muted',
            field=models.BooleanField(default=False, help_text='Mute notifications for this conversation'),
        ),
        migrations.AddIndex(
            model_name='threadparticipant',
            index=models.Index(fields=['user', 'is_archived'], name='messaging_t_user_id_03eb90_idx'),
        ),
    ]
