# Generated by Django 5.2.6 on 2025-11-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_pending_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
