# Generated by Django 5.2.6 on 2025-11-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_is_pending_moderator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_pending_moderator',
            new_name='moderator_approval_pending',
        ),
    ]
