# Generated by Django 5.2.6 on 2025-11-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Account flagged for suspicious activity'),
        ),
        migrations.AddField(
            model_name='profile',
            name='scam_warnings_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of scam/fraud warnings'),
        ),
    ]
