# Generated by Django 5.2.6 on 2025-11-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_bio_profile_interests_profile_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_image_public',
            field=models.BooleanField(default=True),
        ),
    ]
